# Generated by Django 2.2 on 2020-09-29 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start date')),
                ('status', models.CharField(choices=[('IW', 'In work'), ('PL', 'Planned'), ('DN', 'Done'), ('NW', 'New')], default='NW', max_length=2)),
                ('finish_date', models.DateField(blank=True, verbose_name='Finish date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
