# Generated by Django 2.2 on 2020-09-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PL', 'Planned'), ('DN', 'Done'), ('NW', 'New'), ('IW', 'In work')], default='NW', max_length=2),
        ),
    ]
