# Generated by Django 2.2 on 2020-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('IW', 'In work'), ('NW', 'New'), ('PL', 'Planned')], default='NW', max_length=2),
        ),
    ]
