# Generated by Django 2.2 on 2020-10-01 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200930_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytask',
            name='change_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Change date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historytask',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('PL', 'Planned'), ('IW', 'In work'), ('NW', 'New')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('PL', 'Planned'), ('IW', 'In work'), ('NW', 'New')], default='NW', max_length=2),
        ),
    ]
