# Generated by Django 2.2 on 2020-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201001_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytask',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('PL', 'Planned'), ('IW', 'In work'), ('DN', 'Done')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('PL', 'Planned'), ('IW', 'In work'), ('DN', 'Done')], default='NW', max_length=2),
        ),
    ]
